added delete button to delete entries from table
keizerworks/invoicen pull request #33
Opened 2024-11-09 17:25 UTC by sanatan-dive

#Issues Resolved
- added delete button to delete entries from table
- rename dropdow-menu component to dropdown-menu

![oie_jQ59Nq5aN4KQ](https://github.com/user-attachments/assets/4c25195e-c2d9-4ac2-8819-7a965664ffd2)

2024-11-09 19:18 UTC, aayushchugh requested changes
We need this feature for tax table too

2024-11-09 19:27 UTC, aayushchugh requested changes
Please create a new header named `actions` instead of directly showing a 3 dot icon

2024-11-09 19:27 UTC, aayushchugh commented on src/components/ui/triple-dot-dropdown.tsx
> +function FilePenIcon(props: SVGProps<SVGSVGElement>) {
Please remove this unused function

2024-11-09 19:27 UTC, aayushchugh commented on src/components/ui/triple-dot-dropdown.tsx
> +function DeleteIcon(props: SVGProps<SVGSVGElement>) {
Instead of a backspace icon, we need a trash icon

2024-11-09 19:57 UTC, sanatan-dive commented
did the necessary changes
![image](https://github.com/user-attachments/assets/86820e5c-04af-4d79-8abc-433228bbddcf)

2024-11-09 22:06 UTC, sanatan-dive commented
improved trash svg
![image](https://github.com/user-attachments/assets/ea55a695-2abb-449e-b6ec-5d1bdb74a358)

2024-11-10 06:48 UTC, aayushchugh approved these changes
LGTM 🚀

2024-11-10 06:48 UTC, merged